Ques 1

In [1]:
import numpy as np
def add_matrix():
    A=np.matrix(np.random.randint(0,15,12).reshape(3,4))
    B=np.matrix(np.random.randint(15,30,12).reshape(3,4))
    print("The sum of the matrices \n {} \n and \n {} \n is \n {}".format(A,B,A+B))
add_matrix()   

The sum of the matrices 
 [[13  7  5  3]
 [ 0  4  0  0]
 [ 6  1  0 12]] 
 and 
 [[16 26 15 21]
 [29 19 16 26]
 [18 15 15 16]] 
 is 
 [[29 33 20 24]
 [29 23 16 26]
 [24 16 15 28]]


Ques 2

In [2]:
import numpy as np
def multiply_matrix():
    A=np.matrix(np.random.randint(0,10,4).reshape(2,2))
    B=np.matrix(np.random.randint(10,20,4).reshape(2,2))
    print("The sum of the matrices \n {} \n and \n {} \n is\n {}".format(A,B,A*B))
multiply_matrix()   

The sum of the matrices 
 [[5 8]
 [9 4]] 
 and 
 [[18 16]
 [11 16]] 
 is
 [[178 208]
 [206 208]]


Ques 3

In [3]:
import numpy as np
def matrix_transpose():
    X=np.matrix(np.arange(2,41,2).reshape(4,5))
    print("The transpose of the matrix \n {} \n is \n {}".format(X,np.transpose(X)))
matrix_transpose()

The transpose of the matrix 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]] 
 is 
 [[ 2 12 22 32]
 [ 4 14 24 34]
 [ 6 16 26 36]
 [ 8 18 28 38]
 [10 20 30 40]]


Ques 4

In [91]:
words=["Guava","Orange","Apple","Appav","Pomegrante","Jackfruit","Grapes","Mango"]
j=0
for k in range(len(words)):
    for i in range(len(words)-k-1):
        if words[i][j]>words[i+1][j]:
            words[i],words[i+1]=words[i+1],words[i]
        elif words[i][j]==words[i+1][j]:
            for j in range(min(len(words[i]),len(words[i+1]))):
                if words[i][j]>words[i+1][j]:
                    words[i],words[i+1]=words[i+1],words[i]
                    break
                elif words[i][j]==words[i+1][j]:
                    pass
                else:
                    break
            j=0
        else:
            pass

print(words)

['Appav', 'Apple', 'Grapes', 'Guava', 'Jackfruit', 'Mango', 'Orange', 'Pomegrante']


Ques 5

In [92]:
def punc_remove():
    string=input("Enter a string  ")
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for i in string:
        if i in punc:
            string=string.replace(i," ")
    print("THe new string is :",string)

In [93]:
punc_remove()

Enter a string  my name, is "SOua;ranja: @Mishra$
THe new string is : my name  is  SOua ranja   Mishra 
