Q1

In [23]:
C,H=50,30
Q=[]
D=list(map(float,input().split(',')))
for i in range(len(D)):
    Q.append(int(((2*C*D[i])/H)**0.5))
Q1=[str(i) for i in Q]

print(",".join(Q1))

100,150,180
18,22,24


Q2

In [13]:
import numpy as np

X=int(input("Enter the number of rows: "))
Y=int(input("Enter the number of columns: "))

M=np.zeros((X,Y),dtype=int)
for i in range(X):
    for j in range(Y):
        M[i,j]=int(i*j)
print(M)

Enter the number of rows: 3
Enter the number of columns: 5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


Q3

In [33]:
words=list(input().split(","))
words.sort()
print(",".join(words))

without,hello,bag,world
bag,hello,without,world


Q4

In [35]:
words=list(input().split())
words_set=set(words)
words=list(words_set)
words.sort()
print(" ".join(words))

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


Q5

In [49]:
sent=str(input().split())
count_num,count_alp=0,0
for i in sent:
    if 48<=ord(i)<=57:
        count_num+=1
    if 97<=ord(i)<=122 or 65<=ord(i)<=90:
        count_alp+=1
print("LETTERS ",count_alp)
print("DIGITS ",count_num)

hello world! 123
LETTERS  10
DIGITS  3


Q6

In [40]:
abc=['dsad','fref','regregb']

In [52]:
abc=list(input().split(","))
for i in range(len(abc)):
    c1,c2,c3,c4=0,0,0,0
    c5=len(abc[i])
    for j in range(len(abc[i])):
        if 97<=ord(abc[i][j])<=122:
            c1+=1
        if 48<=ord(abc[i][j])<=57:
            c2+=1
        if 65<=ord(abc[i][j])<=90:
            c3+=1
        if abc[i][j]=='$' or abc[i][j]=='#' or abc[i][j]=='@':
            c4+=1
    if c1>=1 and c2>=1 and c3>=1 and c4>=1 and 6<=c5<=12:
        print(abc[i])

ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
